added flag to specify name of backup directory after timestamp

diff --git a/dm/total_dynamix b/dm/total_dynamix
--- a/dm/total_dynamix
+++ b/dm/total_dynamix
@@ -80,7 +80,7 @@ fi
 function backup {
 ## BACK UP FILES ##
 fecho "backing things up..."
-durr=backup/dynamix_$(date -u +"%Y-%m-%dT%H:%M:%SZ")
+durr=backup/dynamix_$(date -u +"%Y-%m-%dT%H:%M:%SZ")_${1}
 mkdir -p $durr
 cp -rf * $durr &> /dev/null
 fecho "all backed up!"
@@ -98,11 +98,31 @@ else
 fi
 }
 
+BACKUP=""
 ### This is where the script actually starts doing things. ###
 
 fecho "dynamix run starting now..."
 fecho ""
 fecho ""
+
+while getopts ":b:" opt; do
+  case ${opt} in
+    b)
+      # specify name of backup directory
+      do_backup=1
+      BACKUP=${OPTARG}
+      ;;
+    \?)
+      echo "Invalid option: -${OPTARG}" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -${OPTARG} requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
+
 
 # if modules are available, try to load them.
 if command -v module &> /dev/null; then
@@ -113,7 +133,7 @@ fi
 [ $do_compile == 1 ] && compile
 [ $do_run == 1 ] && run
 [ $do_plot == 1 ] && plot
-[ $do_backup == 1 ] && backup
+[ $do_backup == 1 ] && backup ${BACKUP}
 
 fecho "all done!"
 fecho ""
